apisix:
  node_listen: 9080
  enable_heartbeat: true
  enable_admin: true
  admin_key: edd1c9f034335f136f87ad84b625c8f1
  admin_listen:
    port: 9180
  allow_admin:
    - 0.0.0.0/0
  enable_debug: true
  enable_dev_mode: true
  config_center: yaml
  yaml_config:
    path: /usr/local/apisix/conf/apisix.yaml

nginx_config:
  http:
    custom_lua_shared_dicts:
      rate_limit: 10m
      ip_restriction: 10m
    lua_shared_dicts:
      - rate_limit: 10m
      - ip_restriction: 10m

deployment:
  admin:
    allow_admin:
      - 0.0.0.0/0
    admin_key:
      - key: edd1c9f034335f136f87ad84b625c8f1
        role: admin
  etcd:
    host:
      - "http://etcd:2379"
    prefix: "/apisix"
    timeout: 30
  log:
    error_log:
      level: warn
      file:
        path: /dev/stderr
    access_log:
      file:
        path: /dev/stdout 